ratings:
  image: registry.demo.opsta.co.th/bookinfo/ratings
  tag: dev
  replicas: 1
  imagePullPolicy: Always
  imagePullSecrets: registry-bookinfo
  requestCpu: 300m
  requestMemory: 128Mi
  limitCpu: 1000m
  limitMemory: 256Mi
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.dev.opsta.co.th
  path: "/ratings(/|$)(.*)"
  serviceType: ClusterIP
  tlsSecret: opsta-bookinfo-dev
extraEnv:
  COMMIT_ID: CHANGE_COMMIT_ID
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://ratings:$(MONGODB_PASSWORD)@bookinfo-dev-ratings-mongodb:27017/ratings
extraSecretEnv:
  MONGODB_PASSWORD:
    bookinfo-dev-ratings-mongodb-secret: mongodb-password
