---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.ingress.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.ratings.port }}
  selector:
    app: {{ .Release.Name }}
