---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bookinfo-ratings
  namespace: training[X]-bookinfo-dev
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://git.demo.opsta.co.th/gitops-devfest-2020/training[X]-ratings.git
  secretRef:
    name: git-ratings
